# Generated by Django 4.2.10 on 2024-07-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='/default.jpg', null=True, upload_to='images/'),
        ),
    ]
