# Generated by Django 4.2.10 on 2024-07-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_api', '0005_alter_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.URLField(default='test', max_length=2000),
        ),
    ]
